backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  site_domain: location.hostname
  base_url: https://api.netlify.com
  api_root: https://api.github.com

# This line should *not* be indented
# publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under images/uploads
public_folder: "img"
site_url: https://keb.now.sh
display_url: https://keb.now.sh

media_library:
  name: kebmedialib

collections:
  - name: "blog"
    label: "keb blogs"
    folder: "content"
    create: true
    format: toml-frontmatter
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }