---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: content
  create: documents
  match: "**/*"
  exclude: _index.md
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NOW_TOKEN=kifAdAVwOhlVXgPMo6rgJtpL
  preview_output_directory: public
  install_dependencies_command: " sudo apt install snapd && sudo snap install --edge
    zola && sudo apt install nodejs && sudo apt install npm && npm i -g now"
  preview_docker_image: https://hub.docker.com/_/ubuntu
  mount_path: "/public"
  working_dir: "/srv"
  instant_preview_command: zola serve
